using System.Diagnostics.CodeAnalysis;

namespace HylianGrimoire.Preview;

internal static class OotPreviewIconCatalog
{
    private static readonly IReadOnlyDictionary<byte, string> RelativePaths = new Dictionary<byte, string>
    {
        [0x00] = @"icon_item_static\gItemIconDekuStickTex.png",
        [0x01] = @"icon_item_static\gItemIconDekuNutTex.png",
        [0x02] = @"icon_item_static\gItemIconBombTex.png",
        [0x03] = @"icon_item_static\gItemIconBowTex.png",
        [0x04] = @"icon_item_static\gItemIconArrowFireTex.png",
        [0x05] = @"icon_item_static\gItemIconDinsFireTex.png",
        [0x06] = @"icon_item_static\gItemIconSlingshotTex.png",
        [0x07] = @"icon_item_static\gItemIconOcarinaFairyTex.png",
        [0x08] = @"icon_item_static\gItemIconOcarinaOfTimeTex.png",
        [0x09] = @"icon_item_static\gItemIconBombchuTex.png",
        [0x0A] = @"icon_item_static\gItemIconHookshotTex.png",
        [0x0B] = @"icon_item_static\gItemIconLongshotTex.png",
        [0x0C] = @"icon_item_static\gItemIconArrowIceTex.png",
        [0x0D] = @"icon_item_static\gItemIconFaroresWindTex.png",
        [0x0E] = @"icon_item_static\gItemIconBoomerangTex.png",
        [0x0F] = @"icon_item_static\gItemIconLensOfTruthTex.png",
        [0x10] = @"icon_item_static\gItemIconMagicBeanTex.png",
        [0x11] = @"icon_item_static\gItemIconHammerTex.png",
        [0x12] = @"icon_item_static\gItemIconArrowLightTex.png",
        [0x13] = @"icon_item_static\gItemIconNayrusLoveTex.png",
        [0x14] = @"icon_item_static\gItemIconBottleEmptyTex.png",
        [0x15] = @"icon_item_static\gItemIconBottlePotionRedTex.png",
        [0x16] = @"icon_item_static\gItemIconBottlePotionGreenTex.png",
        [0x17] = @"icon_item_static\gItemIconBottlePotionBlueTex.png",
        [0x18] = @"icon_item_static\gItemIconBottleFairyTex.png",
        [0x19] = @"icon_item_static\gItemIconBottleFishTex.png",
        [0x1A] = @"icon_item_static\gItemIconBottleMilkFullTex.png",
        [0x1B] = @"icon_item_static\gItemIconBottleRutosLetterTex.png",
        [0x1C] = @"icon_item_static\gItemIconBottleBlueFireTex.png",
        [0x1D] = @"icon_item_static\gItemIconBottleBugTex.png",
        [0x1E] = @"icon_item_static\gItemIconBottlePoeTex.png",
        [0x1F] = @"icon_item_static\gItemIconBottleMilkHalfTex.png",
        [0x20] = @"icon_item_static\gItemIconBottleBigPoeTex.png",
        [0x21] = @"icon_item_static\gItemIconPocketEggTex.png",
        [0x22] = @"icon_item_static\gItemIconChickenTex.png",
        [0x23] = @"icon_item_static\gItemIconZeldasLetterTex.png",
        [0x24] = @"icon_item_static\gItemIconMaskKeatonTex.png",
        [0x25] = @"icon_item_static\gItemIconMaskSkullTex.png",
        [0x26] = @"icon_item_static\gItemIconMaskSpookyTex.png",
        [0x27] = @"icon_item_static\gItemIconMaskBunnyHoodTex.png",
        [0x28] = @"icon_item_static\gItemIconMaskGoronTex.png",
        [0x29] = @"icon_item_static\gItemIconMaskZoraTex.png",
        [0x2A] = @"icon_item_static\gItemIconMaskGerudoTex.png",
        [0x2B] = @"icon_item_static\gItemIconMaskTruthTex.png",
        [0x2C] = @"icon_item_static\gItemIconSoldOutTex.png",
        [0x2D] = @"icon_item_static\gItemIconPocketEggTex.png",
        [0x2E] = @"icon_item_static\gItemIconChickenTex.png",
        [0x2F] = @"icon_item_static\gItemIconCojiroTex.png",
        [0x30] = @"icon_item_static\gItemIconOddMushroomTex.png",
        [0x31] = @"icon_item_static\gItemIconOddPotionTex.png",
        [0x32] = @"icon_item_static\gItemIconPoachersSawTex.png",
        [0x33] = @"icon_item_static\gItemIconBrokenGiantsKnifeTex.png",
        [0x34] = @"icon_item_static\gItemIconPrescriptionTex.png",
        [0x35] = @"icon_item_static\gItemIconEyeballFrogTex.png",
        [0x36] = @"icon_item_static\gItemIconEyeDropsTex.png",
        [0x37] = @"icon_item_static\gItemIconClaimCheckTex.png",
        [0x38] = @"icon_item_static\gItemIconBowFireTex.png",
        [0x39] = @"icon_item_static\gItemIconBowIceTex.png",
        [0x3A] = @"icon_item_static\gItemIconBowLightTex.png",
        [0x3B] = @"icon_item_static\gItemIconSwordKokiriTex.png",
        [0x3C] = @"icon_item_static\gItemIconSwordMasterTex.png",
        [0x3D] = @"icon_item_static\gItemIconSwordBiggoronTex.png",
        [0x3E] = @"icon_item_static\gItemIconShieldDekuTex.png",
        [0x3F] = @"icon_item_static\gItemIconShieldHylianTex.png",
        [0x40] = @"icon_item_static\gItemIconShieldMirrorTex.png",
        [0x41] = @"icon_item_static\gItemIconTunicKokiriTex.png",
        [0x42] = @"icon_item_static\gItemIconTunicGoronTex.png",
        [0x43] = @"icon_item_static\gItemIconTunicZoraTex.png",
        [0x44] = @"icon_item_static\gItemIconBootsKokiriTex.png",
        [0x45] = @"icon_item_static\gItemIconBootsIronTex.png",
        [0x46] = @"icon_item_static\gItemIconBootsHoverTex.png",
        [0x47] = @"icon_item_static\gItemIconBulletBag30Tex.png",
        [0x48] = @"icon_item_static\gItemIconBulletBag40Tex.png",
        [0x49] = @"icon_item_static\gItemIconBulletBag50Tex.png",
        [0x4A] = @"icon_item_static\gItemIconQuiver30Tex.png",
        [0x4B] = @"icon_item_static\gItemIconQuiver40Tex.png",
        [0x4C] = @"icon_item_static\gItemIconQuiver50Tex.png",
        [0x4D] = @"icon_item_static\gItemIconBombBag20Tex.png",
        [0x4E] = @"icon_item_static\gItemIconBombBag30Tex.png",
        [0x4F] = @"icon_item_static\gItemIconBombBag40Tex.png",
        [0x50] = @"icon_item_static\gItemIconGoronsBraceletTex.png",
        [0x51] = @"icon_item_static\gItemIconSilverGauntletsTex.png",
        [0x52] = @"icon_item_static\gItemIconGoldenGauntletsTex.png",
        [0x53] = @"icon_item_static\gItemIconScaleSilverTex.png",
        [0x54] = @"icon_item_static\gItemIconScaleGoldenTex.png",
        [0x55] = @"icon_item_static\gItemIconBrokenGoronsSwordTex.png",
        [0x56] = @"icon_item_static\gItemIconAdultsWalletTex.png",
        [0x57] = @"icon_item_static\gItemIconGiantsWalletTex.png",
        [0x58] = @"icon_item_static\gItemIconDekuSeedsTex.png",
        [0x59] = @"icon_item_static\gItemIconFishingPoleTex.png",
        [0x66] = @"icon_item_24_static\gQuestIconMedallionForestTex.png",
        [0x67] = @"icon_item_24_static\gQuestIconMedallionFireTex.png",
        [0x68] = @"icon_item_24_static\gQuestIconMedallionWaterTex.png",
        [0x69] = @"icon_item_24_static\gQuestIconMedallionSpiritTex.png",
        [0x6A] = @"icon_item_24_static\gQuestIconMedallionShadowTex.png",
        [0x6B] = @"icon_item_24_static\gQuestIconMedallionLightTex.png",
        [0x6C] = @"icon_item_24_static\gQuestIconKokiriEmeraldTex.png",
        [0x6D] = @"icon_item_24_static\gQuestIconGoronRubyTex.png",
        [0x6E] = @"icon_item_24_static\gQuestIconZoraSapphireTex.png",
        [0x6F] = @"icon_item_24_static\gQuestIconStoneOfAgonyTex.png",
        [0x70] = @"icon_item_24_static\gQuestIconGerudosCardTex.png",
        [0x71] = @"icon_item_24_static\gQuestIconGoldSkulltulaTex.png",
        [0x72] = @"icon_item_24_static\gQuestIconHeartContainerTex.png",
        [0x73] = @"icon_item_24_static\gQuestIconHeartPieceTex.png",
        [0x74] = @"icon_item_24_static\gQuestIconDungeonBossKeyTex.png",
        [0x75] = @"icon_item_24_static\gQuestIconDungeonCompassTex.png",
        [0x76] = @"icon_item_24_static\gQuestIconDungeonMapTex.png",
        [0x77] = @"icon_item_24_static\gQuestIconSmallKeyTex.png",
        [0x78] = @"icon_item_24_static\gQuestIconMagicJarSmallTex.png",
        [0x79] = @"icon_item_24_static\gQuestIconMagicJarBigTex.png",
    };

    public static bool TryGetRelativePath(byte value, [NotNullWhen(true)] out string? relativePath)
    {
        return RelativePaths.TryGetValue(value, out relativePath);
    }
}
