namespace HylianGrimoire.Headers.MajorasMask;

public static partial class MmCHeaderExporter
{
    private static readonly IReadOnlyDictionary<string, string> NoArgumentMacros =
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["textspeed"] = "TEXT_SPEED",
            ["hsboatarchery"] = "HS_BOAT_ARCHERY",
            ["strayfairies"] = "STRAY_FAIRIES",
            ["tokens"] = "TOKENS",
            ["pointstens"] = "POINTS_TENS",
            ["pointsthousands"] = "POINTS_THOUSANDS",
            ["break"] = "BOX_BREAK",
            ["break2"] = "BOX_BREAK2",
            ["carriagereturn"] = "CARRIAGE_RETURN",
            ["continue"] = "CONTINUE",
            ["name"] = "NAME",
            ["quicktexton"] = "QUICKTEXT_ENABLE",
            ["quicktextoff"] = "QUICKTEXT_DISABLE",
            ["event"] = "EVENT",
            ["persistent"] = "PERSISTENT",
            ["background"] = "BACKGROUND",
            ["twochoice"] = "TWO_CHOICE",
            ["threechoice"] = "THREE_CHOICE",
            ["timerpostman"] = "TIMER_POSTMAN",
            ["timerminigame1"] = "TIMER_MINIGAME_1",
            ["timer2"] = "TIMER_2",
            ["timermooncrash"] = "TIMER_MOON_CRASH",
            ["timerminigame2"] = "TIMER_MINIGAME_2",
            ["timerhazard"] = "TIMER_ENV_HAZARD",
            ["time"] = "TIME",
            ["chestflags"] = "CHEST_FLAGS",
            ["inputbank"] = "INPUT_BANK",
            ["rupeesselected"] = "RUPEES_SELECTED",
            ["rupeestotal"] = "RUPEES_TOTAL",
            ["timeuntilmooncrash"] = "TIME_UNTIL_MOON_CRASH",
            ["inputdogbet"] = "INPUT_DOGGY_RACETRACK_BET",
            ["inputbombercode"] = "INPUT_BOMBER_CODE",
            ["pausemenu"] = "PAUSE_MENU",
            ["timespeed"] = "TIME_SPEED",
            ["owlwarp"] = "OWL_WARP",
            ["inputlotterycode"] = "INPUT_LOTTERY_CODE",
            ["spiderhousemaskcode"] = "SPIDER_HOUSE_MASK_CODE",
            ["fairieswoodfall"] = "STRAY_FAIRIES_LEFT_WOODFALL",
            ["fairiessnowhead"] = "STRAY_FAIRIES_LEFT_SNOWHEAD",
            ["fairiesgreatbay"] = "STRAY_FAIRIES_LEFT_GREAT_BAY",
            ["fairiesstonetower"] = "STRAY_FAIRIES_LEFT_STONE_TOWER",
            ["pointsboatarchery"] = "POINTS_BOAT_ARCHERY",
            ["lotterycode"] = "LOTTERY_CODE",
            ["lotterycodeguess"] = "LOTTERY_CODE_GUESS",
            ["helditemprice"] = "HELD_ITEM_PRICE",
            ["bombercode"] = "BOMBER_CODE",
            ["event2"] = "EVENT2",
            ["spiderhousemask1"] = "SPIDER_HOUSE_MASK_CODE_1",
            ["spiderhousemask2"] = "SPIDER_HOUSE_MASK_CODE_2",
            ["spiderhousemask3"] = "SPIDER_HOUSE_MASK_CODE_3",
            ["spiderhousemask4"] = "SPIDER_HOUSE_MASK_CODE_4",
            ["spiderhousemask5"] = "SPIDER_HOUSE_MASK_CODE_5",
            ["spiderhousemask6"] = "SPIDER_HOUSE_MASK_CODE_6",
            ["hoursuntilmooncrash"] = "HOURS_UNTIL_MOON_CRASH",
            ["timeuntilnewday"] = "TIME_UNTIL_NEW_DAY",
            ["hsbankrupees"] = "HS_POINTS_BANK_RUPEES",
            ["hspointsunk1"] = "HS_POINTS_UNK_1",
            ["hsfishingpoints"] = "HS_POINTS_FISHING",
            ["hsboatarcherytime"] = "HS_TIME_BOAT_ARCHERY",
            ["hshorseballoontime"] = "HS_TIME_HORSE_BACK_BALLOON",
            ["hslotterytime"] = "HS_TIME_LOTTERY_GUESS",
            ["hstownshooting"] = "HS_TOWN_SHOOTING_GALLERY",
            ["hsunk1"] = "HS_UNK_1",
            ["hsunk3lower"] = "HS_UNK_3_LOWER",
            ["hshorseballoon"] = "HS_HORSE_BACK_BALLOON",
            ["hsdekuplayground1"] = "HS_DEKU_PLAYGROUND_DAY_1",
            ["hsdekuplayground2"] = "HS_DEKU_PLAYGROUND_DAY_2",
            ["hsdekuplayground3"] = "HS_DEKU_PLAYGROUND_DAY_3",
            ["dekuplaygroundname1"] = "DEKU_PLAYGROUND_NAME_DAY_1",
            ["dekuplaygroundname2"] = "DEKU_PLAYGROUND_NAME_DAY_2",
            ["dekuplaygroundname3"] = "DEKU_PLAYGROUND_NAME_DAY_3",
        };
}
